issue_templates:
  bug_report:
    name: Bug Report
    about: Report a bug encountered while operating the platform.
    labels: bug
  story:
    name: Feature Request
    about: Suggest an idea for improving the platform.
    labels: enhancement
  epic:
    name: Epic or Milestone
    about: Used to define larger projects within a single repo consisting of multiple issues.
    labels: epic
  initiative:
    name: Initiative
    about: Used to define larger projects across multiple repos consisting of multiple issues.
    labels: initiative